import { ResultTreeNode } from "../types";

export const testDataSet1: ResultTreeNode[] = [
    {
        id: "root",
        uniqueId: "root",
        import: "test-data/test1.ts",
        type: "Source file",
        extension: "",
        alreadyTraversed: false,
        moduleName: "test-data/test1.ts",
        resolved: true,
        level: 0,
        properties: {},
        imports: [
            {
                id: "fs",
                uniqueId: "2aa9379e-05e2-4f51-9e2d-a0e73483f349",
                import: "fs",
                extension: "",
                alreadyTraversed: false,
                type: "Unknown",
                moduleName: "fs",
                resolved: false,
                imports: [],
                level: 1,
                properties: {},
            },
            {
                id: "src/index.ts",
                uniqueId: "882d8333-b40a-43a5-a291-2f3e2cca2dc5",
                import: "../src/index",
                extension: ".ts",
                alreadyTraversed: false,
                fullPath: "C:\\Source\\ts-insp\\src\\index.ts",
                type: "Source file",
                moduleName: "index",
                resolved: true,
                absolutePath: "src/index.ts",
                imports: [
                    {
                        id: "src/traversal.ts",
                        uniqueId: "38e2dc19-200d-4735-b2b1-e3faae42b316",
                        import: "./traversal",
                        extension: ".ts",
                        alreadyTraversed: false,
                        fullPath: "C:\\Source\\ts-insp\\src\\traversal.ts",
                        type: "Source file",
                        moduleName: "traversal",
                        resolved: true,
                        absolutePath: "src/traversal.ts",
                        imports: [],
                        level: 2,
                        properties: {},
                    },
                    {
                        id: "src/output/console.ts",
                        uniqueId: "2e4c29b0-4f37-4e6f-939c-afff08ba0fc0",
                        import: "./output/console",
                        extension: ".ts",
                        alreadyTraversed: false,
                        fullPath: "C:\\Source\\ts-insp\\src\\output\\console.ts",
                        type: "Source file",
                        moduleName: "console",
                        resolved: true,
                        absolutePath: "src/output/console.ts",
                        imports: [],
                        level: 2,
                        properties: {},
                    },
                    {
                        id: "src/commandLine.ts",
                        uniqueId: "73c2f616-e4b1-49e5-83a7-915fe3c510a0",
                        import: "./commandLine",
                        extension: ".ts",
                        alreadyTraversed: false,
                        fullPath: "C:\\Source\\ts-insp\\src\\commandLine.ts",
                        type: "Source file",
                        moduleName: "commandLine",
                        resolved: true,
                        absolutePath: "src/commandLine.ts",
                        imports: [],
                        level: 2,
                        properties: {},
                    },
                    {
                        id: "src/output/html.ts",
                        uniqueId: "61d1cd4b-c285-4a66-a142-d5f346617ddc",
                        import: "./output/html",
                        extension: ".ts",
                        alreadyTraversed: false,
                        fullPath: "C:\\Source\\ts-insp\\src\\output\\html.ts",
                        type: "Source file",
                        moduleName: "html",
                        resolved: true,
                        absolutePath: "src/output/html.ts",
                        imports: [],
                        level: 2,
                        properties: {},
                    },
                    {
                        id: "src/output/json.ts",
                        uniqueId: "c64ff942-7304-4cb1-98b9-6522d0613529",
                        import: "./output/json",
                        extension: ".ts",
                        alreadyTraversed: false,
                        fullPath: "C:\\Source\\ts-insp\\src\\output\\json.ts",
                        type: "Source file",
                        moduleName: "json",
                        resolved: true,
                        absolutePath: "src/output/json.ts",
                        imports: [],
                        level: 2,
                        properties: {},
                    },
                    {
                        id: "src/output/png.ts",
                        uniqueId: "1b1d7377-a84f-4ba5-9041-7900577d9c7b",
                        import: "./output/png",
                        extension: ".ts",
                        alreadyTraversed: false,
                        fullPath: "C:\\Source\\ts-insp\\src\\output\\png.ts",
                        type: "Source file",
                        moduleName: "png",
                        resolved: true,
                        absolutePath: "src/output/png.ts",
                        imports: [],
                        level: 2,
                        properties: {},
                    },
                    {
                        id: "src/types.d.ts",
                        uniqueId: "816f768f-efbc-4f09-a797-bae9ff22f816",
                        import: "./types",
                        extension: ".d.ts",
                        alreadyTraversed: false,
                        fullPath: "C:\\Source\\ts-insp\\src\\types.d.ts",
                        type: "Source file",
                        moduleName: "types",
                        resolved: true,
                        absolutePath: "src/types.d.ts",
                        imports: [],
                        level: 2,
                        properties: {},
                    },
                ],
                level: 1,
                properties: {},
            },
            {
                id: "src/commandLine.ts",
                uniqueId: "60917fe8-e130-4211-a3d5-530be6dcc8fd",
                import: "../src/commandLine",
                extension: ".ts",
                alreadyTraversed: false,
                fullPath: "C:\\Source\\ts-insp\\src\\commandLine.ts",
                type: "Source file",
                moduleName: "commandLine",
                resolved: true,
                absolutePath: "src/commandLine.ts",
                imports: [
                    {
                        id: "fs",
                        uniqueId: "9fe76181-9167-476e-82b1-825b3c4d6e33",
                        import: "fs",
                        extension: "",
                        alreadyTraversed: false,
                        type: "Unknown",
                        moduleName: "fs",
                        resolved: false,
                        imports: [],
                        level: 2,
                        properties: {},
                    },
                    {
                        id: "node_modules/commander/typings/index.d.ts",
                        uniqueId: "cb973db2-f63c-497a-8169-97de3fb297ff",
                        import: "commander",
                        extension: ".d.ts",
                        alreadyTraversed: false,
                        fullPath: "C:\\Source\\ts-insp\\node_modules\\commander\\typings\\index.d.ts",
                        type: "Node module",
                        moduleName: "commander",
                        resolved: true,
                        absolutePath: "node_modules/commander/typings/index.d.ts",
                        imports: [],
                        level: 2,
                        properties: {},
                    },
                    {
                        id: "src/types.d.ts",
                        uniqueId: "c8dfb5b0-29f7-4f3f-b1e6-891766356f68",
                        import: "./types",
                        extension: ".d.ts",
                        alreadyTraversed: false,
                        fullPath: "C:\\Source\\ts-insp\\src\\types.d.ts",
                        type: "Source file",
                        moduleName: "types",
                        resolved: true,
                        absolutePath: "src/types.d.ts",
                        imports: [],
                        level: 2,
                        properties: {},
                    },
                    {
                        id: "src/tsConfig.ts",
                        uniqueId: "0ee291f3-710b-42b3-9dcd-4880b7323534",
                        import: "./tsConfig",
                        extension: ".ts",
                        alreadyTraversed: false,
                        fullPath: "C:\\Source\\ts-insp\\src\\tsConfig.ts",
                        type: "Source file",
                        moduleName: "tsConfig",
                        resolved: true,
                        absolutePath: "src/tsConfig.ts",
                        imports: [],
                        level: 2,
                        properties: {},
                    },
                    {
                        id: "src/output/log.ts",
                        uniqueId: "02e1e976-9a0f-4ddc-9638-8eea2fc88ae5",
                        import: "./output/log",
                        extension: ".ts",
                        alreadyTraversed: false,
                        fullPath: "C:\\Source\\ts-insp\\src\\output\\log.ts",
                        type: "Source file",
                        moduleName: "log",
                        resolved: true,
                        absolutePath: "src/output/log.ts",
                        imports: [],
                        level: 2,
                        properties: {},
                    },
                ],
                level: 1,
                properties: {},
            },
            {
                id: "src/types.d.ts",
                uniqueId: "a3baf661-463f-4fd3-bb2f-97788599a802",
                import: "../src/types",
                extension: ".d.ts",
                alreadyTraversed: false,
                fullPath: "C:\\Source\\ts-insp\\src\\types.d.ts",
                type: "Source file",
                moduleName: "types",
                resolved: true,
                absolutePath: "src/types.d.ts",
                imports: [
                    {
                        id: "node_modules/typescript/lib/typescript.d.ts",
                        uniqueId: "79f85626-b66d-4648-9294-5bd13badc773",
                        import: "typescript",
                        extension: ".d.ts",
                        alreadyTraversed: false,
                        fullPath: "C:\\Source\\ts-insp\\node_modules\\typescript\\lib\\typescript.d.ts",
                        type: "Node module",
                        moduleName: "typescript",
                        resolved: true,
                        absolutePath: "node_modules/typescript/lib/typescript.d.ts",
                        imports: [],
                        level: 2,
                        properties: {},
                    },
                    {
                        id: "src/output/log.ts",
                        uniqueId: "bec6f59a-040d-406e-977f-3ce77e0e8ef9",
                        import: "./output/log",
                        extension: ".ts",
                        alreadyTraversed: false,
                        fullPath: "C:\\Source\\ts-insp\\src\\output\\log.ts",
                        type: "Source file",
                        moduleName: "log",
                        resolved: true,
                        absolutePath: "src/output/log.ts",
                        imports: [],
                        level: 2,
                        properties: {},
                    },
                ],
                level: 1,
                properties: {},
            },
        ],
    },
];
